### ISSUE TITLE
 java.lang.VerifyError: com/vincentbrison/openlibraries/android/dualcache/lib/DualCache

### ISSUE THREAD

**Issue by luckyliuqi** [vincentbrison/android-easy-cache#13]
Why do I initialize DualCache complains

This is my initialization code

 public void onCreate() {
        super.onCreate();
        DualCacheLogUtils.enableLog();
        DualCacheContextUtils.setContext(getApplicationContext());
        DualCache<String> mCache = new DualCacheBuilder<String>(mCacheId, 2, String.class)
                .useDefaultSerializerInRam(mRamCacheSize)
                .useDefaultSerializerInDisk(mDiskCacheSize, true);
    }

This is the error information

  java.lang.VerifyError: com/vincentbrison/openlibraries/android/dualcache/lib/DualCache
            at com.vincentbrison.openlibraries.android.dualcache.lib.DualCacheBuilder.<init>(DualCacheBuilder.java:18)
            at com.jbp.minegold.MinegoldApplication.onCreate(MinegoldApplication.java:31)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4502)
            at android.app.ActivityThread.access$1300(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5153)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by auchri** [comment]
Try to clear your project and rebuild it.

**Comment by vincentbrison** [comment]
Did the issue solved doing what @auchri said ?

**Comment by luckyliuqi** [comment]
I clean up after the project is still the same，Maybe it's my build.gradle configuration is wrong? But I was written in document steps .

**Comment by vincentbrison** [comment]
From your stacktrace I understand you are initing the cache during a test.
Have you the same issue when initing the cache from your regular
application ?

**Comment by vincentbrison** [comment]
No enought information.

**Comment by yon86** [comment]
@luckyliuqi did u fix this problem. I am getting this problem when I initialize it on my activity

**Comment by yon86** [comment]
@luckyliuqi did u fix this problem. I am getting this problem when I initialize it on my activity

**Comment by vincentbrison** [comment]
@yon86 
Hi,
To have more context and be able to solve this, could you post your stacktrace, your initialization calls and the way you add the library to your gradle ?
BR

**Comment by yon86** [comment]
here is my intialization code

```javascript
cache =  new DualCacheBuilder<ItemResponse>("mainCahche", 1, ItemResponse.class)
                        .useDefaultSerializerInRam(1000)
                        .useDefaultSerializerInDisk(1000, true);
```

in my app gradle file I just added the library path my build tool version is  buildToolsVersion "23.0.1"

```javascript
 compile 'com.vincentbrison.openlibraries.android:dualcache:2.2.2@jar'
```

here is the stack trace
```javascript
  java.lang.VerifyError: com/vincentbrison/openlibraries/android/dualcache/lib/DualCache
                                                                          at com.vincentbrison.openlibraries.android.dualcache.lib.DualCacheBuilder.<init>(DualCacheBuilder.java:18)
                                                                          at com.addiscan.analytics.Activity.SaleActivity.onCreate(SaleActivity.java:124)
                                                                          at android.app.Activity.performCreate(Activity.java:5426)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:161)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:157)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                          at dalvik.system.NativeStart.main(Native Method)

```

**Comment by vincentbrison** [comment]
Thanks for the info, I will look into this ASAP. 
BTW :
- Do you use Progard ? 
- Do you use Java 6 or 7 in your project ?

**Comment by yon86** [comment]
I am not using proguard yet and use java 7 thanks

**Comment by vincentbrison** [comment]
Hi,
I am able to recreate, I will submit a fix ASAP.
BR.

**Comment by vincentbrison** [comment]
The issue is when importing library this way 
`compile 'com.vincentbrison.openlibraries.android:dualcache:2.2.2@jar' the dependencies are not resolved. Thus some class can not be found and you get this `java.lang.VerifyError` error. To resolve this, just import the library without `@jar` :
`compile 'com.vincentbrison.openlibraries.android:dualcache:2.2.2'

**Comment by yon86** [comment]
thank you this fixed my issue
