### ISSUE TITLE
IllegalStateException on reading from Cache 

### ISSUE THREAD

**Issue by hasan-ghaforian** [vincentbrison/android-easy-cache#51]
I have a sample Activity which tries to add Bitmaps to the cache:

```java
   
    DualCache<Bitmap> mCache;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate ( savedInstanceState );
        setContentView ( R.layout.activity_main );

        CacheSerializer<Bitmap> jsonSerializer = new JsonSerializer<> ( Bitmap.class );
        mCache = new Builder<Bitmap> ( CACHE_NAME, TEST_APP_VERSION )
                .enableLog ( )
                .useSerializerInRam ( RAM_MAX_SIZE, jsonSerializer )
                .useSerializerInDisk ( DISK_MAX_SIZE, true, jsonSerializer, getApplicationContext ( ) )
                .build ( );

        Button put  = (Button) findViewById ( R.id.put );
        put.setOnClickListener ( new View.OnClickListener ( ) {
            @Override
            public void onClick(View view) {
                Bitmap bm = BitmapFactory.decodeResource ( getResources ( ), R.mipmap.ic_launcher );
                mCache.put ( "a", bm );
            }
        } );


        Button get = (Button) findViewById ( R.id.get );
        get.setOnClickListener ( new View.OnClickListener ( ) {
            @Override
            public void onClick(View view) {
                Bitmap bitmap = mCache.get ( "a" );
                ImageView imv = (ImageView) findViewById ( R.id.imageView );
                if (bitmap != null) {
                    imv.setImageBitmap ( bitmap );
                }
            }
        } );
    }
```

I first press _put_ button (there is no error) and then _get_. But after pressing _get_ I get this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.IllegalStateException
                      at com.vincentbrison.openlibraries.android.dualcache.JsonSerializer.fromString(JsonSerializer.java:38)
                      at com.vincentbrison.openlibraries.android.dualcache.DualCache.get(DualCache.java:246)
```

**Comment by vincentbrison** [comment]
It is probably because the json serializeris not made for serializing bitmaps. You should implement your own `CacheSerializer` for bitmap, by serializing the bitmap as a byte array, for exemple.

Please keep in mind this library is deprecated. If you want to cache bitmap, you probably want to use libraries like [Picasso](https://github.com/square/picasso) or [Glide](https://github.com/bumptech/glide).

BR.
